-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.

local Utils = _G.LUI.Utils

Utils.CoordsData = {
    [1] = {
        name = "Eriador",
        zones = {
            -- Starting Areas
            {
                name = "Bree-land",
                aliases = { "Breeland" },
                coords = { top = -14.8, left = -67.2, bottom = -38.8, right = -36.4 },
                level = { 1, 25 },
                sub_zones = {
                    {
                        name = "Northern Barrow-downs",
                        aliases = { "Northern Barrows" },
                        coords = { top = -29.9, left = -57.3, bottom = -33.5, right = -52.5 },
                        level = { 20, 25 },
                        sub_zones = {},
                    },
                    {
                        name = "Bree-land Homesteads",
                        aliases = { "Bree-land Homestead" },
                        coords = { top = -33.9, left = -49.9, bottom = -38.0, right = -44.6 },
                        level = { 1, 25 },
                        sub_zones = {},
                    },
                    {
                        name = "Southern Barrow-downs",
                        aliases = { "Southern Barrows" },
                        coords = { top = -32.7, left = -57.8, bottom = -37.1, right = -51.9 },
                        level = { 20, 25 },
                        sub_zones = {},
                    },
                    {
                        name = "Bree",
                        aliases = { "Bree-town" },
                        coords = { top = -28.1, left = -54.6, bottom = -33.2, right = -47.8 },
                        level = { 15, 21 },
                        sub_zones = {},
                    },
                    {
                        name = "Archet Dale",
                        aliases = { "Archet" },
                        coords = { top = -24.2, left = -50.7, bottom = -28.2, right = -45.2 },
                        level = { 1, 15 },
                        sub_zones = {},
                    },
                    {
                        name = "Old Forest",
                        aliases = {},
                        coords = { top = -29.2, left = -65.2, bottom = -38.8, right = -52.4 },
                        level = { 16, 21 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Ered Luin",
                aliases = {},
                coords = { top = -12.4, left = -110.0, bottom = -30.0, right = -86.5 },
                level = { 1, 15 },
                sub_zones = {
                    {
                        name = "Falathlorn Homesteads",
                        aliases = { "Falathlorn Homestead" },
                        coords = { top = -24.3, left = -93.6, bottom = -28.5, right = -88.0 },
                        level = { 1, 15 },
                        sub_zones = {},
                    },
                    {
                        name = "Thorin's Gate",
                        aliases = {},
                        coords = { top = -11.1, left = -106.8, bottom = -17.0, right = -98.7 },
                        level = { 1, 15 },
                        sub_zones = {},
                    },
                    {
                        name = "Thorin's Hall Homesteads",
                        aliases = { "Thorin's Hall Homestead" },
                        coords = { top = -13.2, left = -109.8, bottom = -17.2, right = -104.4 },
                        level = { 1, 15 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Shire",
                aliases = {},
                coords = { top = -23.7, left = -80.3, bottom = -38.9, right = -61.3 },
                level = { 1, 15 },
                sub_zones = {
                    {
                        name = "Shire Homesteads",
                        aliases = { "Shire Homestead" },
                        coords = { top = -34.5, left = -77.4, bottom = -38.9, right = -71.8 },
                        level = { 1, 15 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Swanfleet",
                aliases = {},
                coords = { top = -40.3, left = -45.5, bottom = -67.6, right = -9.1 },
                level = { 1, 15 },
                sub_zones = {
                    {
                        name = "Mossward",
                        aliases = {},
                        coords = { top = -60.2, left = -35.6, bottom = -61.4, right = -34.0 },
                        level = { 1, 15 },
                        sub_zones = {},
                    },
                },
            },
            -- Early Areas
            {
                name = "Cardolan",
                aliases = {},
                coords = { top = -32.9, left = -58.8, bottom = -59.6, right = -23.2 },
                level = { 15, 32 },
                sub_zones = {},
            },
            {
                name = "Lone-lands",
                aliases = {},
                coords = { top = -24.3, left = -43.6, bottom = -40.4, right = -22.1 },
                level = { 20, 35 },
                sub_zones = {},
            },
            {
                name = "North Downs",
                aliases = {},
                coords = { top = -1.3, left = -60.5, bottom = -22.5, right = -32.2 },
                level = { 20, 35 },
                sub_zones = {},
            },
            -- Alphabetic Order
            {
                name = "Angmar",
                aliases = {},
                coords = { top = 14.7, left = -42.8, bottom = -7.3, right = -13.6 },
                level = { 40, 50 },
                sub_zones = {},
            },
            {
                name = "Dunland",
                aliases = {},
                coords = { top = -70.8, left = -28.6, bottom = -90.9, right = 4.1 },
                level = { 65, 72 },
                sub_zones = {
                    {
                        name = "Galtrev",
                        aliases = {},
                        coords = { top = -78.8, left = -18.3, bottom = -81.5, right = -14.8 },
                        level = { 67, 67 },
                        sub_zones = {},
                    },
                    {
                        name = "Tâl Methedras",
                        aliases = { "Tal Methedras" },
                        coords = { top = -72.0, left = -14.5, bottom = -78.8, right = -5.3 },
                        level = { 68, 72 },
                        sub_zones = {},
                    },
                    {
                        name = "Nan Curunír",
                        aliases = { "Nan Curunir" },
                        coords = { top = -76.1, left = -9.5, bottom = -86.3, right = 4.1 },
                        level = { 75, 75 },
                        sub_zones = {
                            {
                                name = "Isengard",
                                aliases = {},
                                coords = { top = -76.3, left = -6.3, bottom = -82.1, right = 1.4 },
                                level = { 75, 75 },
                                sub_zones = {},
                            },
                        },
                    },
                },
            },
            {
                name = "Enedwaith",
                aliases = {},
                coords = { top = -53.9, left = -35.9, bottom = -79.4, right = -1.8 },
                level = { 60, 65 },
                sub_zones = {},
            },
            {
                name = "Eregion",
                aliases = {},
                coords = { top = -38.0, left = -26.8, bottom = -59.6, right = 1.9 },
                level = { 48, 53 },
                sub_zones = {},
            },
            {
                name = "Ettenmoors",
                aliases = {},
                coords = { top = -10.0, left = -24.3, bottom = -22.0, right = -8.2 },
                level = { 160, 160 },
                sub_zones = {},
            },
            {
                name = "Evendim",
                aliases = {},
                coords = { top = -1.6, left = -82.6, bottom = -24.4, right = -52.3 },
                level = { 30, 40 },
                sub_zones = {
                    {
                        name = "Annúminas",
                        aliases = { "Annuminas" },
                        coords = { top = -15.5, left = -73.5, bottom = -21.2, right = -65.9 },
                        level = { 39, 40 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Forochel",
                aliases = {},
                coords = { top = 24.9, left = -92.8, bottom = -5.7, right = -51.9 },
                level = { 44, 50 },
                sub_zones = {},
            },
            {
                name = "Gap of Rohan",
                aliases = {},
                coords = { top = -80.4, left = -20.8, bottom = -95.3, right = -0.9 },
                level = { 73, 74 },
                sub_zones = {},
            },
            {
                name = "Great River",
                aliases = {},
                coords = { top = -17.2, left = -73.9, bottom = -37.6, right = -46.7 },
                level = { 70, 75 },
                sub_zones = {
                    {
                        name = "Stangard",
                        aliases = {},
                        coords = { top = -24.9, left = -65.1, bottom = -27.1, right = -62.2 },
                        level = { 70, 75 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Misty Mountains",
                aliases = {},
                coords = { top = -14.6, left = -11.9, bottom = -33.2, right = 12.9 },
                level = { 40, 45 },
                sub_zones = {},
            },
            {
                name = "Trollshaws",
                aliases = {},
                coords = { top = -22.8, left = -33.4, bottom = -48.3, right = 0.7 },
                level = { 35, 40 },
                sub_zones = {
                    {
                        name = "Angle of Mitheithel",
                        aliases = {},
                        coords = { top = -32.6, left = -27.6, bottom = -47.6, right = -7.6 },
                        level = { 40, 45 },
                        sub_zones = {},
                    },
                    {
                        name = "Rivendell",
                        aliases = { "Rivendell Valley" },
                        coords = { top = -26.3, left = -9.4, bottom = -33.5, right = 0.3 },
                        level = { 37, 40 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Ephel Angren",
                aliases = {},
                coords = { top = 76.4, left = -37.5, bottom = 67.6, right = -25.8 },
                level = { 140, 140 },
                sub_zones = {},
            },
            -- Other
            {
                name = "EB-Helm's Deep",
                aliases = {},
                coords = { top = 72.5, left = -50.9, bottom = 66.0, right = -42.3 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "East Rohan",
                aliases = {},
                coords = { top = -33.6, left = -79.4, bottom = -67.2, right = -34.7 },
                level = { 75, 85 },
                sub_zones = {
                    {
                        name = "Eaves of Fangorn",
                        aliases = {},
                        coords = { top = -34.4, left = -79.4, bottom = -44.3, right = -66.1 },
                        level = { 82, 83 },
                        sub_zones = {},
                    },
                    {
                        name = "Entwash Vale",
                        aliases = {},
                        coords = { top = -38.9, left = -74.3, bottom = -54.6, right = -53.5 },
                        level = { 80, 82 },
                        sub_zones = {},
                    },
                    {
                        name = "East Wall",
                        aliases = {},
                        coords = { top = -45.7, left = -61.3, bottom = -63.5, right = -37.5 },
                        level = { 76, 77 },
                        sub_zones = {},
                    },
                    {
                        name = "Norcrofts",
                        aliases = {},
                        coords = { top = -41.8, left = -67.0, bottom = -58.1, right = -45.3 },
                        level = { 78, 80 },
                        sub_zones = {},
                    },
                    {
                        name = "Sutcrofts",
                        aliases = {},
                        coords = { top = -52.4, left = -69.9, bottom = -67.2, right = -50.1 },
                        level = { 83, 85 },
                        sub_zones = {
                            {
                                name = "Snowbourn",
                                aliases = {},
                                coords = { top = -59.5, left = -63.7, bottom = -62.1, right = -60.3 },
                                level = { 83, 85 },
                                sub_zones = {},
                            },
                        },
                    },
                },
            },
            {
                name = "Helm's Deep (before-dawn)",
                aliases = {},
                coords = { top = 72.5, left = -36.5, bottom = 66.0, right = -27.9 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Helm's Deep (sunrise)",
                aliases = {},
                coords = { top = 72.5, left = -22.1, bottom = 66.0, right = -13.5 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Isengard Depths",
                aliases = {},
                coords = { top = -76.8, left = 31.3, bottom = -81.5, right = 37.5 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Isengard Depths (flooded)",
                aliases = {},
                coords = { top = -69.0, left = 31.3, bottom = -73.6, right = 37.5 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Ring of Isengard",
                aliases = {},
                coords = { top = 62.9, left = 8.1, bottom = 57.1, right = 15.8 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "West Rohan",
                aliases = {},
                coords = { top = -39.3, left = -97.6, bottom = -78.9, right = -44.8 },
                level = { 86, 95 },
                sub_zones = {
                    {
                        name = "Eastfold Hills Homesteads",
                        aliases = {},
                        coords = { top = -62.0, left = -73.5, bottom = -68.4, right = -65.0 },
                        level = { 88, 90 },
                        sub_zones = {},
                    },
                    {
                        name = "Helm's Deep",
                        aliases = {},
                        coords = { top = -60.3, left = -93.3, bottom = -66.8, right = -84.7 },
                        level = { 86, 95 },
                        sub_zones = {},
                    },
                    {
                        name = "Isengard (after)",
                        aliases = {},
                        coords = { top = -42.5, left = -96.9, bottom = -52.9, right = -83.0 },
                        level = { 86, 95 },
                        sub_zones = {},
                    },
                    {
                        name = "Westfold",
                        aliases = {},
                        coords = { top = -52.5, left = -95.2, bottom = -69.4, right = -72.5 },
                        level = { 93, 95 },
                        sub_zones = {},
                    },
                    {
                        name = "Eastfold",
                        aliases = {},
                        coords = { top = -60.0, left = -71.0, bottom = -77.0, right = -48.4 },
                        level = { 88, 90 },
                        sub_zones = {},
                    },
                    {
                        name = "Broadacres",
                        aliases = {},
                        coords = { top = -41.6, left = -78.0, bottom = -53.5, right = -62.1 },
                        level = { 90, 91 },
                        sub_zones = {},
                    },
                    {
                        name = "Kingstead",
                        aliases = {},
                        coords = { top = -50.9, left = -86.6, bottom = -75.6, right = -53.6 },
                        level = { 86, 88 },
                        sub_zones = {
                            {
                                name = "Edoras",
                                aliases = {},
                                coords = { top = -58.2, left = -76.9, bottom = -64.1, right = -69.0 },
                                level = { 86, 88 },
                                sub_zones = {},
                            },
                            {
                                name = "Kingstead Meadows Homesteads",
                                aliases = {},
                                coords = { top = -54.8, left = -73.3, bottom = -60.4, right = -65.9 },
                                level = { 86, 88 },
                                sub_zones = {},
                            },
                        },
                    },
                    {
                        name = "Stonedeans",
                        aliases = {},
                        coords = { top = -44.1, left = -89.2, bottom = -59.4, right = -68.7 },
                        level = { 91, 93 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Wildermore",
                aliases = {},
                coords = { top = -27.1, left = -77.7, bottom = -46.9, right = -51.3 },
                level = { 85, 85 },
                sub_zones = {
                    {
                        name = "Forlaw",
                        aliases = {},
                        coords = { top = -37.4, left = -62.5, bottom = -39.7, right = -59.4 },
                        level = { 85, 85 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Wistmead",
                aliases = {},
                coords = { top = 72.31, left = -116.31, bottom = 69.24, right = -112.21 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Wildwood",
                aliases = { "The Wildwood of Bree-land" },
                coords = { top = -14.0, left = -68.1, bottom = -25.8, right = -52.3 },
                level = { 45, 50 },
                sub_zones = {},
            },
            {
                name = "Entwood",
                aliases = {},
                coords = { top = -37.3, left = -86.6, bottom = -44.7, right = -76.7 },
                level = { 95, 95 },
                sub_zones = {},
            },
            {
                name = "Wold",
                aliases = {},
                coords = { top = -30.1, left = -64.2, bottom = -48.7, right = -39.4 },
                level = { 76, 77 },
                sub_zones = {
                    {
                        name = "Harwick",
                        aliases = {},
                        coords = { top = -37.7, left = -54.4, bottom = -40.8, right = -50.3 },
                        level = { 76, 77 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Icy Crevasse",
                aliases = {},
                coords = { top = 80.1, left = -100.0, bottom = 49.5, right = -59.1 },
                level = { 40, 150 },
                sub_zones = {},
            },
            {
                name = "Yondershire",
                aliases = {},
                coords = { top = -16.4, left = -90.0, bottom = -33.2, right = -67.6 },
                level = { 20, 23 },
                sub_zones = {},
            },
            {
                name = "Attack at Dawn",
                aliases = {},
                coords = { top = 65.4, left = -104.4, bottom = 44.2, right = -76.1 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Defence of the Prancing Pony",
                aliases = { "Thievery and Mischief" },
                coords = { top = 67.1, left = -136.2, bottom = 62.0, right = -129.4 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Glittering Caves",
                aliases = { "Aglarond" },
                coords = { top = -70.2, left = -146.8, bottom = -76.3, right = -138.6 },
                level = { 0, 0 },
                sub_zones = {},
            },
        },
    },
    [2] = {
        name = "Rhovanion",
        zones = {
            -- Zones
            {
                name = "Azanulbizar",
                aliases = { "Azanulbizar, T.A. 2799" },
                coords = { top = 72.4, left = -143.6, bottom = 61.3, right = -128.7 },
                level = { 130, 130 },
                sub_zones = {},
            },
            {
                name = "Elderslade",
                aliases = {},
                coords = { top = 46.6, left = -74.8, bottom = 31.6, right = -54.8 },
                level = { 130, 130 },
                sub_zones = {},
            },
            {
                name = "Ered Mithrin",
                aliases = { "Ered Mithrin and Withered Heath", "Ered Mithrin and the Withered Heath" },
                coords = { top = 46.4, left = -57.2, bottom = 27.2, right = -31.6 },
                level = { 117, 120 },
                sub_zones = {},
            },
            {
                name = "Eryn Lasgalen",
                aliases = { "Eryn Lasgalen and the Dale Lands", "Eryn Lasgalen and the Dale-lands" },
                coords = { top = 37.4, left = -56.6, bottom = 5.3, right = -13.8 },
                level = { 115, 115 },
                sub_zones = {},
            },
            {
                name = "Mount Gundabad",
                aliases = { "Gundabad" },
                coords = { top = 59.0, left = -85.2, bottom = 30.8, right = -46.0 },
                level = { 130, 140 },
                sub_zones = {
                    {
                        name = "Câr Bronach",
                        aliases = { "Car Bronach" },
                        coords = { top = 59.0, left = -77.2, bottom = 44.8, right = -58.2 },
                        level = { 135, 135 },
                        sub_zones = {},
                    },
                    {
                        name = "Welkin-lofts",
                        aliases = {},
                        coords = { top = 52.4, left = -85.2, bottom = 39.6, right = -68.1 },
                        level = { 139, 140 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Delvings of Gundabad",
                aliases = {},
                coords = { top = -32.4, left = -133.8, bottom = -53.2, right = -106.0 },
                level = { 130, 140 },
                sub_zones = {
                    {
                        name = "Deepscrave",
                        aliases = {},
                        coords = { top = -46.8, left = -122.8, bottom = -53.2, right = -114.3 },
                        level = { 133, 133 },
                        sub_zones = {},
                    },
                    {
                        name = "Gloomingtarn",
                        aliases = {},
                        coords = { top = -42.8, left = -128.2, bottom = -51.6, right = -116.5 },
                        level = { 137, 137 },
                        sub_zones = {},
                    },
                    {
                        name = "Pit of Stonejaws",
                        aliases = { "Stonejaws" },
                        coords = { top = -36.4, left = -117.9, bottom = -45.2, right = -106.1 },
                        level = { 134, 134 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Iron Hills",
                aliases = {},
                coords = { top = 33.6, left = -23.6, bottom = 16.9, right = -1.3 },
                level = { 115, 120 },
                sub_zones = {},
            },
            {
                name = "Lothlórien",
                aliases = { "Lothlorien" },
                coords = { top = -4.1, left = -82.5, bottom = -21.7, right = -59.1 },
                level = { 60, 60 },
                sub_zones = {
                    {
                        name = "Caras Galadhon",
                        aliases = {},
                        coords = { top = -12.9, left = -70.0, bottom = -17.1, right = -64.4 },
                        level = { 60, 60 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Mirkwood",
                aliases = {},
                coords = { top = -5.4, left = -62.7, bottom = -22.4, right = -40.1 },
                level = { 60, 65 },
                sub_zones = {},
            },
            {
                name = "Moria",
                aliases = {},
                coords = { top = 2.8, left = -121.6, bottom = -22.8, right = -87.7 },
                level = { 50, 60 },
                sub_zones = {
                    {
                        name = "Durin's Way",
                        aliases = {},
                        coords = { top = 2.0, left = -114.0, bottom = -10.0, right = -98.0 },
                        level = { 53, 53 },
                        sub_zones = {},
                    },
                    {
                        name = "Flaming Deeps",
                        aliases = {},
                        coords = { top = -12.3, left = -112.2, bottom = -18.0, right = -104.7 },
                        level = { 57, 57 },
                        sub_zones = {},
                    },
                    {
                        name = "Foundations of Stone",
                        aliases = {},
                        coords = { top = -10.5, left = -102.9, bottom = -16.4, right = -95.0 },
                        level = { 59, 59 },
                        sub_zones = {},
                    },
                    {
                        name = "Great Delving",
                        aliases = {},
                        coords = { top = -4.9, left = -117.3, bottom = -10.3, right = -110.1 },
                        level = { 51, 51 },
                        sub_zones = {},
                    },
                    {
                        name = "Nud-melek",
                        aliases = {},
                        coords = { top = -3.9, left = -105.3, bottom = -12.2, right = -94.1 },
                        level = { 58, 58 },
                        sub_zones = {},
                    },
                    {
                        name = "Redhorn Lodes",
                        aliases = {},
                        coords = { top = -9.3, left = -109.1, bottom = -16.3, right = -99.8 },
                        level = { 56, 56 },
                        sub_zones = {},
                    },
                    {
                        name = "Silvertine Lodes",
                        aliases = {},
                        coords = { top = -8.5, left = -116.2, bottom = -14.0, right = -108.9 },
                        level = { 52, 52 },
                        sub_zones = {},
                    },
                    {
                        name = "Waterworks",
                        aliases = { "Water-Works", "Water-works" },
                        coords = { top = -11.3, left = -120.5, bottom = -21.7, right = -106.6 },
                        level = { 54, 54 },
                        sub_zones = {},
                    },
                    {
                        name = "Zelem-melek",
                        aliases = {},
                        coords = { top = -3.8, left = -114.0, bottom = -13.8, right = -100.7 },
                        level = { 55, 55 },
                        sub_zones = {},
                    },
                    {
                        name = "Zirakzigil",
                        aliases = {},
                        coords = { top = 17.3, left = -113.0, bottom = 11.6, right = -105.4 },
                        level = { 53, 54 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Vales of Anduin",
                aliases = {},
                coords = { top = 18.3, left = -81.4, bottom = -12.4, right = -40.4 },
                level = { 120, 120 },
                sub_zones = {
                    {
                        name = "Hultvís",
                        aliases = { "Hultvis" },
                        coords = { top = 5.97, left = -55.51, bottom = 4.29, right = -53.27 },
                        level = { 120, 120 },
                        sub_zones = {},
                    },
                    {
                        name = "Meadhollow",
                        aliases = { "Grimbeorn's House" },
                        coords = { top = 15.6, left = -56.7, bottom = 11.6, right = -51.3 },
                        level = { 120, 120 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Wells of Langflood",
                aliases = {},
                coords = { top = 34.6, left = -75.2, bottom = 13.8, right = -47.6 },
                level = { 130, 130 },
                sub_zones = {
                    {
                        name = "Lyndelby Homesteads",
                        aliases = {},
                        coords = { top = 28.6, left = -73.2, bottom = 22.0, right = -64.4 },
                        level = { 130, 130 },
                        sub_zones = {},
                    },
                },
            },
            -- Other
            {
                name = "Clovengap",
                aliases = {},
                coords = { top = -32.2, left = -131.2, bottom = -43.6, right = -116.0 },
                level = { 138, 138 },
                sub_zones = {},
            },
            {
                name = "Bells of Dale",
                aliases = {},
                coords = { top = 65.4, left = -19.0, bottom = 33.3, right = 23.8 },
                level = { 20, 160 },
                sub_zones = {},
            },
            {
                name = "Dol Guldur (razed)",
                aliases = {},
                coords = { top = -11.6, left = -20.4, bottom = -17.0, right = -13.2 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Erebor",
                aliases = {},
                coords = { top = 20.2, left = -144.4, bottom = 12.4, right = -132.7 },
                level = { 115, 115 },
                sub_zones = {
                    {
                        name = "Abodes of Erebor",
                        aliases = {},
                        coords = { top = 20.2, left = -144.4, bottom = 12.4, right = -134.0 },
                        level = { 115, 115 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Felegoth",
                aliases = {},
                coords = { top = 50.0, left = -129.0, bottom = 46.0, right = -123.7 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Frostbluff",
                aliases = {},
                coords = { top = 14.4, left = -96.4, bottom = 10.8, right = -91.6 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Glimmerdeep",
                aliases = {},
                coords = { top = 33.2, left = -139.0, bottom = 29.2, right = -133.7 },
                level = { 115, 120 },
                sub_zones = {},
            },
            {
                name = "Máttugard",
                aliases = { "Mattugard" },
                coords = { top = -43.6, left = -117.6, bottom = -52.4, right = -105.8 },
                level = { 130, 132 },
                sub_zones = {},
            },
            {
                name = "Nud-melek T.A. 1981",
                aliases = {},
                coords = { top = 42.1, left = -143.8, bottom = 34.25, right = -133.5 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Pit of Iron",
                aliases = {},
                coords = { top = 52.3, left = -94.4, bottom = 49.3, right = -90.4 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "The Grand Stair",
                aliases = { "Grand Stair" },
                coords = { top = 73.9, left = -141.5, bottom = 69.2, right = -135.2 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Thikil-gundu",
                aliases = {},
                coords = { top = 26.0, left = -138.7, bottom = 22.0, right = -133.4 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Walls of Moria",
                aliases = {},
                coords = { top = -48.3, left = -9.2, bottom = -54.1, right = -1.5 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "War of Three Peaks",
                aliases = {},
                coords = { top = -87.0, left = -29.2, bottom = -102.0, right = -9.2 },
                level = { 130, 130 },
                sub_zones = {},
            },
            {
                name = "Winterstith",
                aliases = { "The Anvil of Winterstith" },
                coords = { top = 38.6, left = -138.0, bottom = 35.5, right = -133.9 },
                level = { 120, 120 },
                sub_zones = {},
            },
        },
    },
    [3] = {
        name = "Gondor",
        zones = {
            -- Prior to the Battle of Pelennor Fields
            {
                name = "Central Gondor",
                aliases = {},
                coords = { top = -66.6, left = -59.7, bottom = -91.1, right = -26.9 },
                level = { 100, 100 },
                sub_zones = {
                    {
                        name = "Ringló Vale",
                        aliases = { "Ringlo Vale" },
                        coords = { top = -68.5, left = -57.0, bottom = -77.9, right = -44.4 },
                        level = { 100, 100 },
                        sub_zones = {},
                    },
                    {
                        name = "Lebennin",
                        aliases = {},
                        coords = { top = -74.9, left = -48.2, bottom = -88.4, right = -30.2 },
                        level = { 100, 100 },
                        sub_zones = {
                            {
                                name = "Pelargir",
                                aliases = {},
                                coords = { top = -81.8, left = -37.5, bottom = -87.0, right = -30.6 },
                                level = { 100, 100 },
                                sub_zones = {},
                            },
                        },
                    },
                    {
                        name = "Dor-en-Ernil",
                        aliases = {},
                        coords = { top = -75.3, left = -59.2, bottom = -88.0, right = -42.1 },
                        level = { 100, 100 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Eastern Gondor",
                aliases = {},
                coords = { top = -59.1, left = -36.4, bottom = -87.0, right = -0.8 },
                level = { 100, 100 },
                sub_zones = {
                    {
                        name = "Minas Tirith",
                        aliases = {},
                        coords = { top = -62.2, left = -24.1, bottom = -69.0, right = -15.0 },
                        level = { 100, 100 },
                        sub_zones = {},
                    },
                    {
                        name = "Lossarnach",
                        aliases = {},
                        coords = { top = -69.6, left = -32.8, bottom = -82.4, right = -15.8 },
                        level = { 100, 100 },
                        sub_zones = {},
                    },
                    {
                        name = "Upper Lebennin",
                        aliases = {},
                        coords = { top = -73.9, left = -33.2, bottom = -85.2, right = -22.2 }, -- left = -37.4
                        level = { 100, 100 },
                        sub_zones = {},
                    },
                    {
                        name = "Osgiliath",
                        aliases = {},
                        coords = { top = -60.0, left = -13.5, bottom = -66.0, right = -3.9 }, -- top = -58.7
                        level = { 100, 100 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Far Anórien",
                aliases = { "Far Anorien" },
                coords = { top = -32.5, left = -50.4, bottom = -58.1, right = -16.3 },
                level = { 100, 105 },
                sub_zones = {},
            },
            {
                name = "Old Anórien",
                aliases = { "Old Anorien" },
                coords = { top = -44.6, left = -34.0, bottom = -73.8, right = 5.0 },
                level = { 100, 100 },
                sub_zones = {
                    {
                        name = "Pelennor",
                        aliases = {},
                        coords = { top = -58.3, left = -27.8, bottom = -73.2, right = -7.9 },
                        level = { 100, 100 },
                        sub_zones = {},
                    },
                    {
                        name = "Talath Anor",
                        aliases = {},
                        coords = { top = -44.9, left = -26.3, bottom = -62.4, right = -2.9 },
                        level = { 100, 100 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Western Gondor",
                aliases = {},
                coords = { top = -50.5, left = -90.3, bottom = -82.8, right = -47.2 },
                level = { 95, 100 },
                sub_zones = {
                    {
                        name = "Lamedon",
                        aliases = {},
                        coords = { top = -58.3, left = -71.0, bottom = -74.6, right = -49.2 },
                        level = { 97, 98 },
                        sub_zones = {},
                    },
                    {
                        name = "Blackroot Vale",
                        aliases = {},
                        coords = { top = -51.0, left = -83.3, bottom = -71.4, right = -56.0 },
                        level = { 95, 97 },
                        sub_zones = {},
                    },
                    {
                        name = "Havens of Belfalas",
                        aliases = {},
                        coords = { top = -66.9, left = -84.4, bottom = -87.4, right = -57.1 },
                        level = { 98, 100 },
                        sub_zones = {
                            {
                                name = "Dol Amroth",
                                aliases = {},
                                coords = { top = -72.4, left = -74.4, bottom = -77.2, right = -68.0 },
                                level = { 98, 100 },
                                sub_zones = {},
                            },
                        },
                    },
                },
            },
            -- After the Battle of Pelennor Fields
            {
                name = "Anfalas",
                aliases = {},
                coords = { top = -53.9, left = -98.8, bottom = -78.4, right = -66.1 },
                level = { 142, 144 },
                sub_zones = {},
            },
            {
                name = "North Ithilien",
                aliases = {},
                coords = { top = -39.6, left = -28.8, bottom = -67.5, right = 8.4 },
                level = { 105, 105 },
                sub_zones = {},
            },
            {
                name = "South Ithilien",
                aliases = {},
                coords = { top = -60.3, left = -26.5, bottom = -80.1, right = -0.1 },
                level = { 100, 100 },
                sub_zones = {},
            },
            {
                name = "King's Gondor",
                aliases = {},
                coords = { top = -47.5, left = -82.8, bottom = -99.5, right = -13.4 },
                level = { 140, 143 },
                sub_zones = {
                    {
                        name = "Ringló Vale (King's Gondor)",
                        aliases = { "Ringlo Vale (King's Gondor)" },
                        coords = { top = -69.2, left = -57.2, bottom = -78.8, right = -44.4 },
                        level = { 141, 142 },
                        sub_zones = {},
                    },
                    {
                        name = "Upper Lebennin (King's Gondor)",
                        aliases = {},
                        coords = { top = -75.0, left = -36.4, bottom = -85.2, right = -22.8 },
                        level = { 140, 140 },
                        sub_zones = {},
                    },
                    {
                        name = "Dor-en-Ernil (King's Gondor)",
                        aliases = {},
                        coords = { top = -75.6, left = -57.2, bottom = -88.4, right = -40.2 },
                        level = { 141, 142 },
                        sub_zones = {},
                    },
                    {
                        name = "Lossarnach (King's Gondor)",
                        aliases = {},
                        coords = { top = -69.2, left = -34.1, bottom = -82.0, right = -17.0 },
                        level = { 140, 140 },
                        sub_zones = {},
                    },
                    {
                        name = "Lamedon (King's Gondor)",
                        aliases = {},
                        coords = { top = -59.5, left = -67.6, bottom = -73.2, right = -49.4 },
                        level = { 141, 142 },
                        sub_zones = {},
                    },
                    {
                        name = "Blackroot Vale (King's Gondor)",
                        aliases = {},
                        coords = { top = -53.3, left = -77.2, bottom = -67.6, right = -58.2 },
                        level = { 141, 142 },
                        sub_zones = {},
                    },
                    {
                        name = "Lower Lebennin (King's Gondor)",
                        aliases = {},
                        coords = { top = -69.3, left = -52.5, bottom = -87.6, right = -28.1 },
                        level = { 140, 140 },
                        sub_zones = {
                            {
                                name = "Pelargir (King's Gondor)",
                                aliases = {},
                                coords = { top = -79.6, left = -38.0, bottom = -86.8, right = -28.4 },
                                level = { 140, 140 },
                                sub_zones = {},
                            },
                        },
                    },
                    {
                        name = "Cape of Belfalas",
                        aliases = { "Bay of Belfalas" },
                        coords = { top = -76.4, left = -78.9, bottom = -96.6, right = -51.9 },
                        level = { 142, 143 },
                        sub_zones = {
                            {
                                name = "Cape of Belfalas Homesteads",
                                aliases = {},
                                coords = { top = -80.0, left = -77.6, bottom = -94.6, right = -58.1 },
                                level = { 142, 143 },
                                sub_zones = {},
                            },
                        },
                    },
                },
            },
            {
                name = "Pinnath Gelin",
                aliases = {},
                coords = { top = -46.8, left = -100.4, bottom = -66.7, right = -73.8 },
                level = { 143, 145 },
                sub_zones = {},
            },
            {
                name = "Wastes",
                aliases = {},
                coords = { top = -26.1, left = -17.0, bottom = -41.5, right = 3.4 },
                level = { 105, 105 },
                sub_zones = {
                    {
                        name = "Battle of the Morannon",
                        aliases = { "Battle of Morannon" },
                        coords = { top = -32.4, left = -11.4, bottom = -40.9, right = 0.0 },
                        level = { 105, 105 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Pelennor (After Battle)",
                aliases = { "Pelennor Fields (After-battle)" },
                coords = { top = -54.5, left = -28.2, bottom = -72.9, right = -3.6 },
                level = { 105, 105 },
                sub_zones = {
                    {
                        name = "Minas Tirith (After-battle)",
                        aliases = {},
                        coords = { top = -62.2, left = -24.1, bottom = -69.0, right = -15.0 },
                        level = { 105, 105 },
                        sub_zones = {},
                    },
                    {
                        name = "Osgiliath (After Battle)",
                        aliases = {},
                        coords = { top = -59.6, left = -13.2, bottom = -65.1, right = -5.7 },
                        level = { 105, 105 },
                        sub_zones = {},
                    },
                },
            },
            -- Other
            {
                name = "At the Stone of Erech",
                aliases = {},
                coords = { top = -92.6, left = -106.9, bottom = -113.0, right = -79.6 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Beacon Hills",
                aliases = {},
                coords = { top = -31.8, left = -51.3, bottom = -50.4, right = -26.5 },
                level = { 103, 104 },
                sub_zones = {},
            },
            {
                name = "Belfalas (King's Gondor)",
                aliases = { "Belfalas" },
                coords = { top = -69.2, left = -84.1, bottom = -94.8, right = -50.0 },
                level = { 142, 143 },
                sub_zones = {
                    {
                        name = "Dol Amroth (King's Gondor)",
                        aliases = {},
                        coords = { top = -72.0, left = -76.4, bottom = -78.0, right = -68.4 },
                        level = { 142, 143 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Dead Marshes",
                aliases = {},
                coords = { top = -25.0, left = -19.5, bottom = -32.0, right = -10.2 },
                level = { 100, 100 },
                sub_zones = {},
            },
            {
                name = "Field of Onslaught",
                aliases = {},
                coords = { top = 29.6, left = -27.8, bottom = 14.7, right = -7.9 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Hammer of the Underworld",
                aliases = { "Defence of Minas Tirith" },
                coords = { top = 62.6, left = -24.1, bottom = 55.8, right = -15.0 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Kings' End",
                aliases = {},
                coords = { top = 29.6, left = -27.8, bottom = 14.7, right = -7.9 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "March of the King",
                aliases = {},
                coords = { top = -39.6, left = -34.8, bottom = -71.9, right = 8.2 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Minas Tirith (Midsummer)",
                aliases = {},
                coords = { top = 26.9, left = -62.0, bottom = 18.8, right = -51.2 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Minas Tirith Besieged",
                aliases = {},
                coords = { top = 62.6, left = 12.7, bottom = 55.8, right = 21.8 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Morannon",
                aliases = {},
                coords = { top = 67.0, left = -12.1, bottom = 55.4, right = 3.4 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Outer Gondor",
                aliases = {},
                coords = { top = -46.8, left = -101.2, bottom = -73.2, right = -66.0 },
                level = { 142, 145 },
                sub_zones = {},
            },
            {
                name = "Paths of the Dead",
                aliases = { "Paths of Dead" },
                coords = { top = -42.0, left = -78.3, bottom = -46.8, right = -71.9 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Retaking Dol Amroth",
                aliases = {},
                coords = { top = -32.4, left = -130.4, bottom = -37.2, right = -124.0 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Riders' Stand",
                aliases = {},
                coords = { top = 29.6, left = -27.8, bottom = 14.7, right = -7.9 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Ruin of Pel Dúven",
                aliases = { "Ruin of Pel Duven" },
                coords = { top = 29.6, left = -27.8, bottom = 14.7, right = -7.9 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Sundering of Osgiliath",
                aliases = {},
                coords = { top = 66.0, left = -87.1, bottom = 58.8, right = -77.5 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Taur Drúadan",
                aliases = { "Taur Druadan" },
                coords = { top = -42.5, left = -33.9, bottom = -58.2, right = -12.9 },
                level = { 101, 102 },
                sub_zones = {},
            },
            {
                name = "Threshold of the City",
                aliases = { "Threshold of City" },
                coords = { top = 29.6, left = -27.8, bottom = 14.7, right = -7.9 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Throne of the Dread Terror",
                aliases = { "Throne of Dread Terror" },
                coords = { top = 26.1, left = -54.6, bottom = 21.3, right = -48.1 },
                level = { 0, 0 },
                sub_zones = {},
            },
        },
    },
    [4] = {
        name = "Mordor",
        zones = {
            -- Zones
            {
                name = "Gorgoroth",
                aliases = { "Plateau of Gorgoroth" },
                coords = { top = -35.3, left = -6.0, bottom = -69.4, right = 39.5 },
                level = { 105, 115 },
                sub_zones = {
                    {
                        name = "Udûn",
                        aliases = { "Udun" },
                        coords = { top = -36.7, left = -4.3, bottom = -49.0, right = 12.0 },
                        level = { 106, 108 },
                        sub_zones = {},
                    },
                    {
                        name = "Dor Amarth",
                        aliases = {},
                        coords = { top = -37.1, left = 5.9, bottom = -54.6, right = 29.3 },
                        level = { 108, 109 },
                        sub_zones = {},
                    },
                    {
                        name = "Talath Úrui",
                        aliases = { "Talath Urui" },
                        coords = { top = -47.9, left = 6.7, bottom = -66.0, right = 30.8 },
                        level = { 112, 113 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Mordor Besieged",
                aliases = {},
                coords = { top = -88.6, left = -134.0, bottom = -105.7, right = -111.3 },
                level = { 120, 122 },
                sub_zones = {},
            },
            {
                name = "Morgul Vale",
                aliases = { "Imlad Morgul" },
                coords = { top = -56.4, left = -12.5, bottom = -77.9, right = 16.2 },
                level = { 120, 130 },
                sub_zones = {
                    {
                        name = "Minas Morgul",
                        aliases = {},
                        coords = { top = -64.6, left = -1.4, bottom = -70.0, right = 5.9 },
                        level = { 126, 130 },
                        sub_zones = {},
                    },
                },
            },
            -- Other
            {
                name = "Agarnaith",
                aliases = {},
                coords = { top = -41.9, left = 18.2, bottom = -58.0, right = 39.8 },
                level = { 114, 115 },
                sub_zones = {},
            },
            {
                name = "Eithel Gwaur",
                aliases = {},
                coords = { top = 62.4, left = 54.7, bottom = 59.4, right = 58.7 },
                level = { 122, 150 },
                sub_zones = {},
            },
            {
                name = "End of All Things",
                aliases = {},
                coords = { top = -45.5, left = -129.0, bottom = -57.8, right = -112.6 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Harrowing of Morgul",
                aliases = {},
                coords = { top = 61.0, left = -139.0, bottom = 55.6, right = -131.7 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Kâm Lagúrz",
                aliases = {},
                coords = { top = 35.5, left = 15.7, bottom = 13.6, right = 44.9 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Lhingris",
                aliases = {},
                coords = { top = -45.0, left = -6.5, bottom = -66.9, right = 22.7 },
                level = { 110, 111 },
                sub_zones = {},
            },
            {
                name = "Nargroth",
                aliases = {},
                coords = { top = 19.5, left = 11.1, bottom = 15.0, right = 17.2 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Orodruin",
                aliases = { "Mount Doom" },
                coords = { top = -45.5, left = 11.0, bottom = -57.8, right = 27.4 },
                level = { 115, 115 },
                sub_zones = {},
            },
            {
                name = "Sammath Naur",
                aliases = {},
                coords = { top = 35.8, left = 30.8, bottom = 32.2, right = 35.6 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Shelob's Lair",
                aliases = {},
                coords = { top = 28.9, left = -147.9, bottom = 16.4, right = -131.2 },
                level = { 0, 0 },
                sub_zones = {},
            },
            {
                name = "Torech Ungol",
                aliases = {},
                coords = { top = 36.0, left = 9.0, bottom = 29.6, right = 17.6 },
                level = { 0, 0 },
                sub_zones = {},
            },
        },
    },
    [5] = {
        name = "Haradwaith",
        zones = {
            -- Zones
            {
                name = "Adagím",
                aliases = { "Adagim" },
                coords = { top = -30.7, left = -58.7, bottom = -54.8, right = -26.6 },
                level = { 151, 153 },
                sub_zones = {},
            },
            {
                name = "Ambarûl",
                aliases = { "Ambarul" },
                coords = { top = -9.2, left = -97.5, bottom = -32.4, right = -66.6 },
                level = { 150, 150 },
                sub_zones = {},
            },
            {
                name = "An Shêru",
                aliases = { "An Sheru" },
                coords = { top = -45.2, left = -86.1, bottom = -65.2, right = -59.5 },
                level = { 156, 158 },
                sub_zones = {},
            },
            {
                name = "Cape of Umbar",
                aliases = {},
                coords = { top = -8.0, left = -118.0, bottom = -30.7, right = -87.7 },
                level = { 147, 150 },
                sub_zones = {
                    {
                        name = "Umbar Baharbêl",
                        aliases = { "Umbar Baharbel" },
                        coords = { top = -15.6, left = -106.8, bottom = -27.6, right = -90.9 },
                        level = { 150, 150 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Mûr Ghala",
                aliases = { "Mur Ghala" },
                coords = { top = -20.2, left = -99.6, bottom = -73.6, right = -28.3 },
                level = { 151, 159 },
                sub_zones = {},
            },
            {
                name = "Idagâl",
                aliases = { "Idagal" },
                coords = { top = -40.7, left = -110.2, bottom = -70.8, right = -70.0 },
                level = { 158, 159 },
                sub_zones = {
                    {
                        name = "Emax Dûl",
                        aliases = { "Emax Dul" },
                        coords = { top = -62.0, left = -92.4, bottom = -69.2, right = -82.8 },
                        level = { 158, 159 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Imhûlar",
                aliases = { "Imhular" },
                coords = { top = -25.2, left = -79.1, bottom = -48.4, right = -48.2 },
                level = { 150, 150 },
                sub_zones = {},
            },
            {
                name = "Kighân",
                aliases = { "Kighan" },
                coords = { top = -46.0, left = -70.5, bottom = -69.2, right = -39.6 },
                level = { 153, 156 },
                sub_zones = {
                    {
                        name = "Zajâna",
                        aliases = { "Kighan Zajana", "Kighân Zajâna", "Zajana" },
                        coords = { top = -61.1, left = -67.6, bottom = -67.7, right = -58.8 },
                        level = { 153, 156 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Khûd Zagin",
                aliases = {},
                coords = { top = -22.0, left = -97.4, bottom = -48.4, right = -62.6 },
                level = { 150, 150 },
                sub_zones = {},
            },
            {
                name = "Fearwater",
                aliases = { "Sug Nidar", "Sûg Nidar" },
                coords = { top = -16.5, left = -49.9, bottom = -37.2, right = -22.4 },
                level = { 159, 160 },
                sub_zones = {},
            },
            {
                name = "Umbar-môkh",
                aliases = { "Umbar-mokh" },
                coords = { top = -111.6, left = -149.6, bottom = -123.6, right = -133.6 },
                level = { 150, 150 },
                sub_zones = {
                    {
                        name = "Dil-irmíz",
                        aliases = { "Dil-irmiz" },
                        coords = { top = -118.8, left = -146.1, bottom = -123.6, right = -139.7 },
                        level = { 150, 150 },
                        sub_zones = {},
                    },
                    {
                        name = "Ilmabiri",
                        aliases = {},
                        coords = { top = -113.2, left = -146.3, bottom = -118.0, right = -139.9 },
                        level = { 150, 150 },
                        sub_zones = {},
                    },
                    {
                        name = "Kamrabezûr",
                        aliases = { "Kamrabezur" },
                        coords = { top = -112.8, left = -142.7, bottom = -118.3, right = -135.3 },
                        level = { 150, 150 },
                        sub_zones = {},
                    },
                    {
                        name = "Khabârkhad",
                        aliases = { "Khabarkhad" },
                        coords = { top = -116.4, left = -144.7, bottom = -121.2, right = -138.3 },
                        level = { 150, 150 },
                        sub_zones = {},
                    },
                    {
                        name = "Tâkhdar",
                        aliases = { "Takhdar" },
                        coords = { top = -111.9, left = -146.0, bottom = -118.3, right = -137.4 },
                        level = { 150, 150 },
                        sub_zones = {},
                    },
                },
            },
            {
                name = "Urash Dâr",
                aliases = { "Urash Dar" },
                coords = { top = -10.8, left = -76.7, bottom = -34.0, right = -45.7 },
                level = { 150, 150 },
                sub_zones = {},
            },
            {
                name = "Zîrar Tarka",
                aliases = { "Shield Isles", "Shield Isles of Umbar", "Zirar Tarka" },
                coords = { top = 8.7, left = -141.7, bottom = -16.4, right = -108.3 },
                level = { 145, 147 },
                sub_zones = {
                    {
                        name = "Furtherholm (Zír Aktar)",
                        aliases = { "Furtherholm", "Furtherholm (Zir Aktar)", "Zir Aktar", "Zír Aktar" },
                        coords = { top = -0.4, left = -124.3, bottom = -6.8, right = -115.7 },
                        level = { 0, 0 },
                        sub_zones = {},
                    },
                },
            },
            -- Other
            {
                name = "Valley of Ikorbân",
                aliases = { "Valley of Ikorban" },
                coords = { top = -6.0, left = -99.3, bottom = -48.3, right = -42.9 },
                level = { 150, 150 },
                sub_zones = {},
            },
        },
    },
    [14] = {
        name = "Tales of Yore",
        zones = {
        },
    },
    [0] = {
        name = "Unassigned",
        zones = {
            -- TODO: needs manual confirmation
            {
                name = "Dunlending",
                aliases = {},
                coords = { top = -70.5, left = -27.7, bottom = -95.0, right = 4.2 },
                level = { 0, 0 },
                sub_zones = {},
            },
        },
    },
}
