-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- GENERATED by LUI data tools -- DO NOT EDIT
-- Source: LOTRO game client data
local D = {}
D.count = 20467
D.base_id = 1879048195
D.id_width = 3
D.ord_width = 3
D.off_width = 4
D.ref_base = 1879000000
-- record order: level ascending, then folded en name
D.widths = { category = 2, count = 4, deed = 1, event = 1, flags = 1, level = 2, lock = 1, n = 1, qty = 3, ref = 3, tier = 2, times = 1 }
D.section_sep = ""
D.text_sep = ""
D.sub_sep = ""
D.langs = { "de", "en", "fr" }
_G.LoreData = _G.LoreData or {}
_G.LoreData["Quests.manifest"] = D
return D
