-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- GENERATED by LUI data tools -- DO NOT EDIT
-- Source: LOTRO game client data
local D = {}
D.count = 8634
D.base_id = 1879048194
D.id_width = 3
D.text_sep = ""
D.langs = { "de", "en", "es", "fr" }
_G.LoreData = _G.LoreData or {}
_G.LoreData["Npcs.manifest"] = D
return D
