-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- GENERATED by LUI data tools -- DO NOT EDIT
-- Source: LOTRO game client data
local D = {}
D.count = 4484
D.buff_count = 1528
D.base_id = 1879048830
D.id_width = 3
D.e_base_id = 1879049270
D.e_id_width = 3
D.cat_width = 2
D.eff_ord_width = 2
D.roff_width = 2
D.icon_width = 5
D.dur_width = 3
D.langs = { "de", "en", "es", "fr" }
_G.LoreData = _G.LoreData or {}
_G.LoreData["Skills.manifest"] = D
return D
