-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.

-- the builtin wiki bestiary is packed (src/Data/Bestiary, generated by
-- tools/lore2lua from .data/lore/bestiary.json); bestiary_db registers a proxy
-- at DB.en.bestiary and loads the blobs on first access
import "LUI.src.Data.bestiary_db"
import "LUI.src.Encyclopedia.drop_table"
pcall(import, "LUI.src.Encyclopedia.drop_table_de")
pcall(import, "LUI.src.Encyclopedia.drop_table_fr")
import "LUI.src.Encyclopedia.data_resolver"
import "LUI.src.Encyclopedia.data_access"
import "LUI.src.Encyclopedia.card_widgets"
import "LUI.src.Encyclopedia.browser_shared"
import "LUI.src.Encyclopedia.bestiary_card"
import "LUI.src.Encyclopedia.resource_card"
import "LUI.src.Encyclopedia.bestiary_tracker"
import "LUI.src.Encyclopedia.item_browser"
import "LUI.src.Encyclopedia.quest_browser"
import "LUI.src.Encyclopedia.quest_card"
import "LUI.src.Encyclopedia.encyclopedia_window"
