-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- GENERATED by LUI data tools -- DO NOT EDIT
-- Source: LOTRO game client data
local D = {}
D.count = 7791
D.base_id = 1879054944
D.id_width = 3
D.off_width = 3
D.item_base = 1879000000
D.widths = { bonus = 2, category = 2, cooldown = 3, crit = 1, flags = 1, item = 3, n = 1, pack_count = 1, profession = 1, qty = 2, tier = 1, xp = 2 }
D.enums = { profession = { "COOK", "FARMER", "FORESTER", "JEWELLER", "METALSMITH", "PROSPECTOR", "SCHOLAR", "TAILOR", "WEAPONSMITH", "WOODWORKER" } }
D.langs = { "de", "en", "es", "fr" }
_G.LoreData = _G.LoreData or {}
_G.LoreData["Recipes.manifest"] = D
return D
