-- This Source Code Form is subject to the terms of the Mozilla Public
-- License, v. 2.0. If a copy of the MPL was not distributed with this
-- file, You can obtain one at https://mozilla.org/MPL/2.0/.
--
-- GENERATED by LUI data tools -- DO NOT EDIT
-- Source: LOTRO game client data
local D = {}
D.count = 12333
D.ref_width = 3
D.ord_width = 3
D.off_width = 4
D.koff_width = 3
D.loff_width = 3
D.goff_width = 3
D.l_width = 2
D.m_width = 5
D.p_width = 4
D.di_base = 1879048195
D.di_width = 3
D.qi_width = 3
D.aliases = {
["bratha tasakh, lady of many venoms"] = "Bratha Tasakh (Remmorchant)",
["cursed rider"] = "The Cursed Rider (Mordor Besieged)",
["gârash, the emptiness (phase 1)"] = "Gârash, the Emptiness",
["gârash, the emptiness (phase 2)"] = "Gârash, the Emptiness (The Temple of Utug-bûr)",
["krahjarn mender"] = "Krajarn Mender",
["lieutenant of dol guldur"] = "The Lieutenant of Dol Guldur (Mirkwood)",
["lieutenant of dol guldur (dol guldur)"] = "The Lieutenant of Dol Guldur (Mirkwood)",
["lieutenant of dol guldur (parth daenath)"] = "The Cursed Rider (Mordor Besieged)",
["lieutenant of dol guldur (the fallen kings)"] = "The Cursed Rider (Fallen Kings)",
["the cursed rider"] = "The Cursed Rider (Mordor Besieged)",
["the lieutenant of dol guldur"] = "The Lieutenant of Dol Guldur (Mirkwood)",
["the witch-king"] = "The Witch-king (Mordor Besieged)",
["white hand firecaller"] = "White Hand Fire-caller",
["white hand solider"] = "White Hand Soldier (Mission)",
["witch-king"] = "The Witch-king (Mordor Besieged)",
["witch-king of angmar"] = "Witch-king of Angmar (Minas Tirith)",
["witch-king of angmar (emyn duir)"] = "The Witch-king (Mordor Besieged)",
["witch-king of angmar (minas tirith besieged)"] = "Witch-king of Angmar (Minas Tirith)",
["witch-king of angmar (the fallen kings)"] = "The Witch-king (Fallen Kings)",
}
_G.LoreData = _G.LoreData or {}
_G.LoreData["Bestiary.manifest"] = D
return D
